### PR TITLE
Add option for parsing figureProps

### PR DESCRIPTION
**Pull request by ellell**
Type: Minor
Review: @iefserge

### CODE REVIEW

**Comment by iefserge** [comment]
@ellell why do we want this to be optional? should we parse by default?
otherwise lgtm

**Comment by ellell** [comment]
@iefserge I think not parsing by default is nice, because it's an easy way to clean up the html, and I think we should keep that as the default. By doing this optionally we can explicitly parse the attributes we need though.

**Comment by iefserge** [comment]
But in this case we can't store articles in json since we still need original html?

**Comment by iefserge** [comment]
sorry, misunderstood the purpose of this option
LGTM

**Pull request merged**
